version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    container_name: rabbit-mq
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123456"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management Plugin port
    networks:
      - rabbitmq-network
    restart: always

volumes:
  volume:

networks:
  rabbitmq-network:
    name: rabbitmq-network
    driver: bridge