version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    container_name: rabbit-mq
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123456"
    volumes:
          - rabbitmq-driver:/var/lib/rabbitmq    # use a volume to store the data    
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management Plugin port
    networks:
      - rabbitmq-network
    restart: always

volumes:
    rabbitmq-driver:
      driver: local
      name : rabbitmq-driver

networks:
  rabbitmq-network:
    name: rabbitmq-network
    driver: bridge