@HostAddress = http://localhost:5002
@home = http://localhost:5002/swagger/
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSm9obkRvZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImJldDFAU3BvcnRiZXQuY29tIiwidS1pZCI6IjEiLCJ1LXBob25lIjoiMTIzNDU2Nzg5IiwidS1uYW1lIjoiSm9obkRvZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJBZG1pbiIsIlVzZXIiXSwibXktc2NvcGUiOiJjYW5Xcml0ZSIsImV4cCI6MTcxMTQ2NzgyNywiaXNzIjoiaHR0cHM6Ly9zcG9ydGJldC5jb20iLCJhdWQiOiJzcG9ydGJldCBBdWRpZW5jZSJ9.PJIWzXaIlj11dEDddj_eRlBqjkD3NAlwO0OdzM6ZEs8
### 
GET {{HostAddress}}/team
Accept: application/json
Authorization: Bearer {{Token}}
###   
POST {{HostAddress}}/team
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
  "name": "Yam Football club",
  "ShortName": "YFC"
}

#login
### 
POST {{HostAddress}}/Auth
Content-Type: application/json

{
  "username": "JohnDoe",
  "password": "123456"
}

### get-cards
GET {{HostAddress}}/Bet/get-cards
Accept: application/json
Authorization: Bearer {{Token}}
### 
POST {{HostAddress}}/Bet/create-match-selection HTTP/1.1
Accept: application/json
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "name": "Game ON!",
  "description": "Week 3",
  "activeUntil": "2024-02-24T21:58:04.970Z",
  "matches": [
    9,8
  ],
  "matchesTypes": [
    1,2,3
  ]
}
######
POST {{HostAddress}}/Bet/create-match-selection HTTP/1.1
Accept: application/json
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "name": "Firday Game 3",
  "description": "Firday Week 3",
  "activeUntil": "2024-01-23T21:58:04.970Z",
  "matches": [
    1,2,3,4
  ],
  "matchesTypes": [
    1,2,3
  ]
}
###
@matchtypeid = 1
PUT {{HostAddress}}/Bet/update-bet-result/{{matchtypeid}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "matchTypeId": 3,
  "matchSelectionId": 1,
  "matchId": 4,
  "outcomeId": 1
}