@HostAddress = http://localhost:5002
@home = http://localhost:5002/swagger/
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSm9obkRvZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImJldDFAU3BvcnRiZXQuY29tIiwidS1pZCI6IjEiLCJ1LXBob25lIjoiMTIzNDU2Nzg5IiwidS1uYW1lIjoiSm9obkRvZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJBZG1pbiIsIlVzZXIiXSwiZXhwIjoxNzAyNTQ2MzQxLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwiYXVkIjoiU2FtcGxlQXVkaWVuY2UifQ.vjvCcTQD2TSbLW9mLvof4tNn1X7m9rccxahO-FzaU4c
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2FtdGVkbGEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJiZXQyQFNwb3J0YmV0LmNvbSIsInUtaWQiOiIyIiwidS1waG9uZSI6Ijk1NTMzODM4MyIsInUtbmFtZSI6InNhbXRlZGxhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIkFkbWluIiwiVXNlciIsImNhbldyaXRlIl0sIm15LXNjb3BlIjoiY2FuV3JpdGUiLCJleHAiOjE3MDI1NjQzMDEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJTYW1wbGVBdWRpZW5jZSJ9.gRkAnAB7MozqzRsCKFrqRBEBUAmsTong4ArG4YN51lg
### weatherforecast   
GET {{HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{Token}}
### 
GET {{HostAddress}}/team
Accept: application/json
Authorization: Bearer {{Token}}
###   
POST {{HostAddress}}/team
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
  "name": "Yam Football club",
  "ShortName": "YFC"
}

#login
### 
POST {{HostAddress}}/login
Content-Type: application/json

#{
#  "username": "JohnDoe",
#  "password": "123456"
#}
{
  "username": "samtedla",
  "password": "thecars"
}
### match
GET {{HostAddress}}/match
Accept: application/json
Authorization: Bearer {{Token}}

###
POST {{HostAddress}}/match
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
  "homeTeamId": 7,
  "awayTeamId": 9,
  "matchDate": "2021-05-02T00:00:00"
}

### odd  
GET {{HostAddress}}/odd
Accept: application/json
Authorization: Bearer {{Token}}

###  
POST {{HostAddress}}/odd
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
  "name": "More",
  "oddsType": 2
}
### Fixture 
POST {{HostAddress}}/fixture
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

{
  "oddsId": 3,
  "matchId": 2,
  "date": "2023-12-12T18:49:02.323Z"
}

### get-cards
GET {{HostAddress}}/Bet/get-cards
Accept: application/json
Authorization: Bearer {{Token}}

