

POST /Bet/create-match-selection HTTP/1.1
{
  "name": "Sunday Game 1",
  "description": "Sunday Week 2",
  "activeUntil": "2024-01-24T21:58:04.970Z",
  "matches": [
    5,6,7,8,9
  ],
  "matchesTypes": [
    1,2,3
  ]
}

####    
post https://localhost:65415/createbook HTTP/1.1
Accept: application/json

{
    "Title":"Samson 9",
    "Author":"Harry Potter"
}