version: '3.8'

services:
  vue-app:
    container_name: vue-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
    networks:
      - grpc-nginx-network

networks:
   grpc-nginx-network:
    name:  grpc-nginx-network