version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
    #environment:
    #  - NODE_ENV=development
    networks:
      - grpc-nginx-network

networks:
   grpc-nginx-network:
    name:  grpc-nginx-network