x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
swagger: 2.0
info:
  title: PizzaStore Web Api
  version: 1.0.0
consumes:
- application/json
produces:
- application/json
paths:
  /Bet/get-cards:
    get:
      tags:
      - Bet
      operationId: Bet_GetBets
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/MyBets'
  /Bet/get-card/{id}:
    get:
      tags:
      - Bet
      operationId: Bet_GetBet
      parameters:
      - type: integer
        name: id
        in: path
        required: true
        format: int32
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/MyBet'
  /Bet/get-card-extended/{id}:
    get:
      tags:
      - Bet
      operationId: Bet_GetBetExtended
      parameters:
      - type: integer
        name: id
        in: path
        required: true
        format: int32
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/MyBetExtende'
  /Bet/get-active-bets:
    get:
      tags:
      - Bet
      operationId: Bet_GetAviliableBets
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/GetActivBetsResponse'
  /Bet/create-match-selection:
    post:
      tags:
      - Bet
      operationId: Bet_CreateMatchSelection
      parameters:
      - type: string
        name: EqualityContract
        in: query
        x-nullable: false
      - type: string
        name: Name
        in: query
        x-nullable: false
      - type: string
        name: Description
        in: query
        x-nullable: false
      - type: string
        name: ActiveUntil
        in: query
        format: date-time
        x-nullable: false
      - type: array
        name: Matches
        in: query
        collectionFormat: multi
        x-nullable: false
        items:
          type: integer
          format: int32
      - type: array
        name: MatchesTypes
        in: query
        collectionFormat: multi
        x-nullable: false
        items:
          type: integer
          format: int32
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/CreateMatchSelectionsResponse'
  /Bet/bet-on:
    post:
      tags:
      - Bet
      operationId: Bet_BetOnSelection
      parameters:
      - type: string
        name: EqualityContract
        in: query
        x-nullable: false
      - type: integer
        name: SelectionId
        in: query
        format: int32
        x-nullable: false
      - type: integer
        name: MatchTypeId
        in: query
        format: int32
        x-nullable: false
      - type: array
        name: Matches
        in: query
        collectionFormat: multi
        x-nullable: false
        items:
          $ref: '#/definitions/MatchRequest'
      - type: number
        name: Amount
        in: query
        format: decimal
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/BetOnGameResponse'
  /Bet/get-bet-result/{id}:
    get:
      tags:
      - Bet
      operationId: Bet_GetBetResult
      parameters:
      - type: integer
        name: id
        in: path
        required: true
        format: int32
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/BetResultResponse'
  /Bet/get-match-selections:
    get:
      tags:
      - Bet
      operationId: Bet_GetMatchSelectionsAll
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/GetActiveMatchs'
  /Bet/get-match-selections/{id}:
    get:
      tags:
      - Bet
      operationId: Bet_GetMatchSelections
      parameters:
      - type: integer
        name: id
        in: path
        required: true
        format: int32
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/GetActiveMatch'
  /Bet/get-match-types:
    get:
      tags:
      - Bet
      operationId: Bet_GetMatchTypesAll
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/GetMatchTypes'
  /Bet/get-match-types/{id}:
    get:
      tags:
      - Bet
      operationId: Bet_GetMatchTypes
      parameters:
      - type: integer
        name: id
        in: path
        required: true
        format: int32
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/GetMatchTypes'
  /Bet/get-outcomes:
    get:
      tags:
      - Bet
      operationId: Bet_GetOutcomes
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/GetOutcomes'
  /Bet/update-bet-result/{matchtypeid}:
    put:
      tags:
      - Bet
      operationId: Bet_UpdateBetResult
      parameters:
      - type: integer
        name: matchtypeId
        in: path
        required: true
        format: int32
        x-nullable: false
      - type: string
        name: EqualityContract
        in: query
        x-nullable: false
      - type: integer
        name: MatchTypeId
        in: path
        required: true
        format: int32
        x-nullable: false
      - type: integer
        name: MatchSelectionId
        in: query
        format: int32
        x-nullable: false
      - type: integer
        name: MatchId
        in: query
        format: int32
        x-nullable: false
      - type: integer
        name: OutcomeId
        in: query
        format: int32
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/UpdateBetResult'
  /Auth:
    post:
      tags:
      - Auth
      operationId: Auth_Login
      parameters:
      - name: request
        in: body
        schema:
          $ref: '#/definitions/LoginRequest'
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/AuthenticationResult'
  /Auth/add-user:
    post:
      tags:
      - Auth
      operationId: Auth_AddUser
      parameters:
      - name: request
        in: body
        schema:
          $ref: '#/definitions/AddUserRequest'
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/AddUserResponse'
  /Auth/update-user:
    put:
      tags:
      - Auth
      operationId: Auth_UpdateUser
      parameters:
      - name: request
        in: body
        schema:
          $ref: '#/definitions/UpdateUserRequest'
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/UpdateUserResponse'
  /Auth/change-password:
    put:
      tags:
      - Auth
      operationId: Auth_ChangePassword
      parameters:
      - name: request
        in: body
        schema:
          $ref: '#/definitions/ChangePasswordRequest'
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/ChangePasswordResponse'
  /Team:
    get:
      tags:
      - Team
      operationId: Team_GetTeams
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/TeamResponse'
    post:
      tags:
      - Team
      operationId: Team_AddTeam
      parameters:
      - type: string
        name: EqualityContract
        in: query
        x-nullable: false
      - type: string
        name: Name
        in: query
        x-nullable: false
      - type: string
        name: ShortName
        in: query
        x-nullable: false
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/TeamResponse'
definitions:
  MyBets:
    type: object
    required:
    - BetCardId
    - MatchSelectionId
    - MatchTypeId
    - MatchSelection
    - MatchType
    properties:
      BetCardId:
        type: integer
        format: int32
      MatchSelectionId:
        type: integer
        format: int32
      MatchTypeId:
        type: integer
        format: int32
      MatchSelection:
        type: string
      MatchType:
        type: string
  MyBet:
    type: object
    required:
    - BetCardId
    - MatchId
    - HomeTeam
    - Home
    - AwayTeam
    - Away
    - MatchType
    - OutcomeId
    - OutcomeName
    - CreatedAt
    - MatchSelectionId
    - MatchSelectionName
    - MatchSelectionDescription
    properties:
      BetCardId:
        type: integer
        format: int32
      MatchId:
        type: integer
        format: int32
      HomeTeam:
        type: string
      Home:
        type: string
      AwayTeam:
        type: string
      Away:
        type: string
      MatchType:
        type: string
      OutcomeId:
        type: integer
        format: int32
      OutcomeName:
        type: string
      CreatedAt:
        type: string
        format: date-time
      MatchSelectionId:
        type: integer
        format: int32
      MatchSelectionName:
        type: string
      MatchSelectionDescription:
        type: string
  MyBetExtende:
    type: object
    required:
    - BetCardId
    - CreatedAt
    - MatchSelectionId
    - MatchSelectionName
    - MatchSelectionDescription
    - BetAmount
    - WonAmount
    - TotalWinCount
    - MatchType
    - Matches
    properties:
      BetCardId:
        type: integer
        format: int32
      CreatedAt:
        type: string
        format: date-time
      MatchSelectionId:
        type: integer
        format: int32
      MatchSelectionName:
        type: string
      MatchSelectionDescription:
        type: string
      BetAmount:
        type: number
        format: decimal
      WonAmount:
        type: number
        format: decimal
      TotalWinCount:
        type: integer
        format: int32
      MatchType:
        type: string
      Matches:
        type: array
        items:
          $ref: '#/definitions/MyBetMatchExtend'
  MyBetMatchExtend:
    type: object
    required:
    - MatchId
    - HomeTeam
    - Home
    - AwayTeam
    - Away
    - OutcomeId
    - OutcomeName
    - MatchResultId
    - MatchResult
    properties:
      MatchId:
        type: integer
        format: int32
      HomeTeam:
        type: string
      Home:
        type: string
      AwayTeam:
        type: string
      Away:
        type: string
      OutcomeId:
        type: integer
        format: int32
      OutcomeName:
        type: string
      MatchResultId:
        type: integer
        format: int32
      MatchResult:
        type: string
  GetActivBetsResponse:
    type: object
    required:
    - Id
    - Name
    - Description
    - TypeName
    - IsEnabled
    properties:
      Id:
        type: integer
        format: int32
      Name:
        type: string
      Description:
        type: string
      TypeName:
        type: string
      IsEnabled:
        type: boolean
  CreateMatchSelectionsResponse:
    type: object
    required:
    - MatchSelectionId
    - StatusName
    - IsSaved
    properties:
      MatchSelectionId:
        type: integer
        format: int32
      StatusName:
        type: string
      IsSaved:
        type: boolean
  BetOnGameResponse:
    type: object
    required:
    - StatusName
    - IsSaved
    properties:
      StatusName:
        type: string
      IsSaved:
        type: boolean
  MatchRequest:
    type: object
    required:
    - MatchId
    - OutcomeId
    properties:
      MatchId:
        type: integer
        format: int32
      OutcomeId:
        type: integer
        format: int32
  BetResultResponse:
    type: object
    required:
    - Matches
    - BetAmount
    - WonAmount
    - TotalWinCount
    - CardId
    - MatchSelectionId
    - MatchTypeId
    properties:
      Matches:
        type: array
        items:
          $ref: '#/definitions/MatchResponse'
      BetAmount:
        type: number
        format: decimal
      WonAmount:
        type: number
        format: decimal
      TotalWinCount:
        type: integer
        format: int32
      CardId:
        type: integer
        format: int32
      MatchSelectionId:
        type: integer
        format: int32
      MatchTypeId:
        type: integer
        format: int32
  MatchResponse:
    type: object
    required:
    - MatchId
    - OutcomeId
    - MatchResultId
    - MatchResult
    properties:
      MatchId:
        type: integer
        format: int32
      OutcomeId:
        type: integer
        format: int32
      MatchResultId:
        type: integer
        format: int32
      MatchResult:
        type: string
  GetActiveMatchs:
    type: object
    required:
    - MatchSelectionId
    - Name
    - Description
    - IsEnabled
    properties:
      MatchSelectionId:
        type: integer
        format: int32
      Name:
        type: string
      Description:
        type: string
      IsEnabled:
        type: boolean
  GetActiveMatch:
    type: object
    required:
    - MatchSelectionId
    - Name
    - Description
    - ActiveUntil
    - Matches
    properties:
      MatchSelectionId:
        type: integer
        format: int32
      Name:
        type: string
      Description:
        type: string
      ActiveUntil:
        type: string
        format: date-time
      Matches:
        type: array
        items:
          $ref: '#/definitions/SelectionMatchResponse'
  SelectionMatchResponse:
    type: object
    required:
    - MatchSelectionId
    - MatchId
    - HomeId
    - Home
    - HomeTeam
    - AwayId
    - AwayTeam
    - Away
    - MatchDate
    properties:
      MatchSelectionId:
        type: integer
        format: int32
      MatchId:
        type: integer
        format: int32
      HomeId:
        type: integer
        format: int32
      Home:
        type: string
      HomeTeam:
        type: string
      AwayId:
        type: integer
        format: int32
      AwayTeam:
        type: string
      Away:
        type: string
      MatchDate:
        type: string
        format: date-time
  GetMatchTypes:
    type: object
    required:
    - MatchTypeId
    - Name
    properties:
      MatchTypeId:
        type: integer
        format: int32
      Name:
        type: string
  GetOutcomes:
    type: object
    required:
    - Id
    - OutcomeId
    - Name
    - IsEnabled
    properties:
      Id:
        type: integer
        format: int32
      OutcomeId:
        type: integer
        format: int32
      Name:
        type: string
      IsEnabled:
        type: boolean
  UpdateBetResult:
    type: object
    required:
    - Message
    properties:
      Message:
        type: string
  AuthenticationResult:
    type: object
    required:
    - Token
    - UserId
    properties:
      Token:
        type: string
      UserId:
        type: integer
        format: int32
  LoginRequest:
    type: object
    required:
    - Username
    - Password
    properties:
      Username:
        type: string
      Password:
        type: string
  AddUserResponse:
    type: object
    required:
    - Id
    - StatusName
    properties:
      Id:
        type: integer
        format: int32
      StatusName:
        type: string
  AddUserRequest:
    type: object
    required:
    - Username
    - Password
    - FirstName
    - MiddleName
    - LastName
    - PhoneNumber
    - Email
    properties:
      Username:
        type: string
      Password:
        type: string
      FirstName:
        type: string
      MiddleName:
        type: string
      LastName:
        type: string
      PhoneNumber:
        type: string
      Email:
        type: string
  UpdateUserResponse:
    type: object
    required:
    - Id
    - StatusName
    properties:
      Id:
        type: integer
        format: int32
      StatusName:
        type: string
  UpdateUserRequest:
    type: object
    required:
    - Id
    - Username
    - Password
    - FirstName
    - MiddleName
    - LastName
    - PhoneNumber
    - Email
    properties:
      Id:
        type: integer
        format: int32
      Username:
        type: string
      Password:
        type: string
      FirstName:
        type: string
      MiddleName:
        type: string
      LastName:
        type: string
      PhoneNumber:
        type: string
      Email:
        type: string
  ChangePasswordResponse:
    type: object
    required:
    - Id
    - StatusName
    properties:
      Id:
        type: integer
        format: int32
      StatusName:
        type: string
  ChangePasswordRequest:
    type: object
    required:
    - Password
    - NewPassword
    properties:
      Password:
        type: string
      NewPassword:
        type: string
  TeamResponse:
    type: object
    required:
    - Id
    - Name
    - ShortName
    properties:
      Id:
        type: integer
        format: int32
      Name:
        type: string
      ShortName:
        type: string
